AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - db/migrate/schema.rb
    - db/migrate/20160126231731_devise_create_users.rb
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  Enabled: false
